{% set name = "pycomlink" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pycomlink/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 91d74d34121ed7d85e6b5870d23c40d9d6656b5ba9b2387ceb31c8fe72dc001a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - scipy
    - pandas >=0.22
    - matplotlib-base
    - numba
    - folium
    - h5py
    - xarray
    - shapely
    - pyproj
    - tqdm
    - pykrige
    - future

test:
  imports:
    - pycomlink

about:
  home: http://github.com/pycomlink/pycomlink
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Tools for processing microwave link attenuation data for rainfall estimation

extra:
  recipe-maintainers:
    - cchwala
