{% set name = "pycomlink" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pycomlink/{{ name }}/archive/{{ version }}.tar.gz
  sha256: adee6e4c94be07d84a43115ff75990b4f5f63a7f190d757ae842e964196f1ea1

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy
    - scipy
    - pandas
    - matplotlib-base
    - numba
    - h5py
    - xarray
    - sparse
    - netcdf4
    - shapely
    - pyproj
    - tqdm
    - pykrige
    - future
    - scikit-learn
    - bottleneck
    - poligrain

test:
  requires:
    - python {{ python_min }}
  imports:
    - pycomlink

about:
  home: http://github.com/pycomlink/pycomlink
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Tools for processing microwave link attenuation data for rainfall estimation

extra:
  recipe-maintainers:
    - cchwala
